name: "Test Loads Image"
on:
  push:
    branches:
      - main
      - develop
      
jobs:
  Unit-Test:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Instance Name
        run: ls /usr/local/opt/runner/settings/instancename
      - name: Execute test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project "GHEnvTesting.xcodeproj" -scheme "GHEnvTesting" -destination "OS=14.4,name=iPhone 12 Pro" | xcpretty
